user:
  yangyang1:
    username: 18322369885
    password: YANGyang022
  yangyang2:
    username: 15620849885
    password: YANGyang022
management:
  test1:
    username: test
    password: liufenceshi123
url: https://bss-front-uat.sixents.com
managementUrl: https://bss-backend-uat.sixents.com/login
mysql:
  uat:
    host: bj-cdb-b5o7vu30.sql.tencentcdb.com
    port: 60507
    username: qa_zhangning
    password: vGT&MVC2h3A6@MLP
    datebase: bss
redis:
  host: 192.168.0.104
  port: 6379
  db: 0
GGA: $GPGGA,025006.78,4007.5533880,N,11627.9528726,E,1,00,1.0,109.077,M,-9.077,M,0.0,*54
headless: False